### ISSUE TITLE
Remove requirement for element parameter

### ISSUE THREAD

**Issue by joshuabaker** [aelvan/Similar-Craft#3]
I’ve encountered a scenario where requiring the `element` parameter is problematic — I’m wanting to get entries of a certain type related to the supplied `context`.

Looking through `SimilarService` it looks like it’d be possible to exclude that requirement if the `criteria` parameter is supplied. Exclusion can still be achieved via the `criteria` (i.e. `id: 'not ' ~ element.id`).

Can you see an issues here?

**Comment by aelvan** [comment]
Not sure I understand the use case, can you elaborate on this part: "I’m wanting to get entries of a certain type related to the supplied context."

**Comment by joshuabaker** [comment]
There’s several scenarios that exist when passing in an element would not be ideal. Take the example below. I don’t want to have to exclude an entry in this instance.

``` php
{% set productsRelatedToColours = craft.similar.find({
  context: entry.selectedColours,
  criteria: craft.commerce.products
}) %}
```

**Comment by aelvan** [comment]
I see. What Similar is meant to do is "get entries that are similiar to this entry based on context" (replace entry with any element type). Without the `element`, the "...similar to this entry..." goes out the window. If I understand it correctly, you want to "get products based on how many of these colors they have related to them"? Intrinsically related to `entry`, but only because that's where you get the `selectedColours` from?

Anyways, I think the solution would be to get the element type from the criteria instead of the element, if that doesn't exist. Try replacing the next to last line with:

`$modelname = '\Craft\Similar_Similar'.(isset($element) ? $element->elementType : $criteria->getElementType()->classHandle).'Model';`

Haven't tested it with craft commerce, but seems to work on entries.

**Comment by joshuabaker** [comment]
You got it. The entry itself, in my example, could also potentially be returned.

I couldn’t figure out how to build that class name when exploring removing the requirement for `element`, however your response has the answer; `$criteria->elementType->classHandle`. I might be able to piece together a working PR now.

**Comment by aelvan** [comment]
Yeah, it feels a bit weird that it's `$element->elementType` and `$criteria->elementType->classHandle`. I don't really get why that would be different..? Might be worth digging into whether that actually is the correct way to get the element type from a criteria.

**Comment by aelvan** [comment]
> You got it. The entry itself, in my example, could also potentially be returned.

Just one note. Not sure what you meant here, but note that it's not possible in Craft to return different element types in the same element criteria. So there's no way you'd be able to get both entries and products returned from Similar. :)

**Comment by joshuabaker** [comment]
Yeah. That’s not the aim. Criteria passed in would define type coming out.

Theoretically that could work though, leveraging reflection somehow. That’s a different topic though! 😅
